#!/bin/sh
set -eu
PREFIX="/run/lxd-agent"

# Functions.
mount_virtiofs() {
    /usr/bin/mount -t virtiofs config "${PREFIX}/.mnt" >/dev/null 2>&1
}

mount_9p() {
    /usr/sbin/modprobe 9pnet_virtio >/dev/null 2>&1 || true
    /usr/bin/mount -t 9p config "${PREFIX}/.mnt" -o access=0,trans=virtio,size=1048576 >/dev/null 2>&1
}

fail() {
    /usr/bin/umount -l "${PREFIX}" >/dev/null 2>&1 || true
    /usr/bin/rmdir "${PREFIX}" >/dev/null 2>&1 || true
    echo "${1}"
    exit 1
}

# Setup the mount target.
/usr/bin/umount -l "${PREFIX}" >/dev/null 2>&1 || true
/usr/bin/mkdir -p "${PREFIX}"
/usr/bin/mount -t tmpfs tmpfs "${PREFIX}" -o mode=0700,size=50M
/usr/bin/mkdir -p "${PREFIX}/.mnt"

# Try virtiofs first.
mount_virtiofs || mount_9p || fail "Couldn't mount virtiofs or 9p, failing."

# Copy the data.
/usr/bin/cp -Ra "${PREFIX}/.mnt/"* "${PREFIX}"

# Unmount the temporary mount.
/usr/bin/umount "${PREFIX}/.mnt"
/usr/bin/rmdir "${PREFIX}/.mnt"

# Fix up permissions.
/usr/bin/chown -R root:root "${PREFIX}"

exit 0